version: 0.2
phases:
  install:
    commands:
      - docker pull selenium/standalone-chrome:latest
  pre_build:
    commands:
      - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm --name selenium selenium/standalone-chrome:latest
  build:
    commands:
      - mvn clean install test
  post_build:
    commands:
      #    - docker exec selenium pgrep ffmpeg > pidfile
artifacts:
  base-directory: /tmp
  files:
    - '*.png'
reports:
  Selenium:
    file-format: TESTNGXML
    files:
      - target/surefire-reports/testng-results.xml
